apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
  labels: {{ include "myapp.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 8080;
      gzip  on;
      index index.html;
      location = /stub_status {
        stub_status  on;
        default_type text/plain;
        access_log   off;
        allow        127.0.0.1;
        deny all;
      }

      location / {
        root /usr/share/nginx/html;
         try_files $uri $uri/ /index.html =404;
      }

    }

