
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "myapp.fullname" . }}
  labels: {{ include "myapp.labels" . | nindent 4 }}
    # labels defined in spec.serviceMonitorSelector.matchLabels
    release: monitoring
spec:
  endpoints:
    - port: metrics
      scheme: http
      interval: 15s
      scrapeTimeout: 14s
      interval: 15s
      scrapeTimeout: 14s
  selector:
    matchLabels:
    {{- include "myapp.selectorLabels" . | nindent 5 }}
