apiVersion: v1
kind: Service
metadata:
  name: myapp-desa
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-desa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-desa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-desa
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-desa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/instance: myapp-desa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/instance: myapp-desa
    spec:
      containers:
        - name: myapp
          image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: '1'
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 128Mi
